== Integrating Netty

Netty is one of the dependencies of Vert.x. In fact, Netty powers the networking services of Vert.x. Vert.x Core
provides the basic network services one can expect from such library:

- TCP
- HTTP
- UDP
- DNS

These are built built with various components from Netty. The Netty community has implemented a wide
range of components and this chapter explains how to integrate such components in Vert.x.

This chapter shows the integration of a https://tools.ietf.org/html/rfc868[TIME] prococol client/server. The Netty
documentation provides client/server implementations of this protocol, we will focus on the integration of these
components.

=== The TIME server

The original server example can be found http://netty.io/wiki/user-guide-for-4.x.html#wiki-h3-9[here].

The Vert.x timer server exposes a very simple API:

- a static method for creating a `TimeServer`
- the server `listen` and `close` life cycle methods
- the `requestHandler` for setting

[source,java]
----
{@link org.vietj.vertx.nettyserver.TimeServer}
----

A TIME server serving the current JVM time is then straighforward to implement:

[source,java]
----
{@link org.vietj.vertx.nettyserver.TimeServerExample#main}
----

Let's study now how this server can be implemented integrating the existing Netty implementation with Vert.x:

[source,java]
----
{@link org.vietj.vertx.nettyserver.impl.TimeServerImpl}
----

The first point in this example is the usage of Vert.x `ContextInternal`, an extension of the
`io.vertx.core.Context` interface exposing the necessary bits for integrating the Netty API.

The context is obtained with `Vertx#getOrCreateContext()` method that returns the current execution context
or create a new one if necessary.

When used in a Verticle, `getOrCreateContext` return the context of this Verticle, when used in a non Vert.x
thread like a `main` or a unit test, it creates a new one and returns it.

Such context is always associated with a Netty event loop and thus using this context ensures our server
use the same event loop if one existed before or use a new one.

The method `ContextInternal#nettyEventLoop()` returns this particular event loop and we can use it when the
`ServerBoostrap` is created.

Now that we are more intimate with `ContextInternal`, let's talk of the `ContextInternal#executeFromIO(ContextTask)`
method. The `executeFromIO` method needs to be used when our server invokes application code, usually an handler
provided by the application before starting the server:

- listen handler
- request handler
- close handler
- etc...

When the context task is called, `executeFromIO` ensures that the current thread will be associated with
the execution context. Any uncaught exception thrown by this block will also be reported on the context, usually
such exception is either logged or passed to the `Context#exceptionHandler`.

We use `executeFromIO` to dispatch the result to the `listenHandler` to the application is aware of the bind result.

Now let's finish our server with the `TimeServerHandler`, which is pretty much an adaptation of the Netty's
original http://netty.io/wiki/user-guide-for-4.x.html#wiki-h3-9[`TimeServerHandler`]:

[source,java]
----
{@link org.vietj.vertx.nettyserver.impl.TimeServerHandler}
----

Again here, we notice the usage of `executeFromIO` when a TIME request happens, the future to be completed is
passed to the `requestHandler`.

=== The TIME client

The original client example can be found http://netty.io/wiki/user-guide-for-4.x.html#wiki-h3-10[here].

The Vert.x timer client exposes a very simple API:

- a static method for creating a `TimeClient`
- the client `getTime` method for retrieving a time value from a server

[source,java]
----
{@link org.vietj.vertx.nettyclient.TimeClient}
----

The TIME client is straightforward to use:

[source,java]
----
{@link org.vietj.vertx.nettyclient.TimeClientExample#main}
----

Let's study now how this client can be implemented integrating the existing Netty implementation with Vert.x:

[source,java]
----
{@link org.vietj.vertx.nettyclient.impl.TimeClientImpl}
----

Like in the server example we use the `ContextInternal` to obtain Netty's `EventLoop` to set on the `Bootstrap`.

The bootstrap setup is very similar to the original example, in case of a failure the application callback
uses again `executeFromIO` for the same reason thatn before.

The `TimeClientHandler` integration uses also `executeFromIO` for calling back the application:

[source,java]
----
{@link org.vietj.vertx.nettyclient.impl.TimeClientHandler}
----
