= Integrating Netty
Julien Viet <julien@julienviet.com>

Netty is one of the dependencies of Vert.x. In fact, Netty powers the networking services of Vert.x. Vert.x Core
provides the basic network services one can expect from such library:

- TCP
- HTTP
- UDP
- DNS

These are built built with various components from Netty. The Netty community has implemented a wide
range of components and this chapter explains how to integrate such components in Vert.x.

This chapter shows the integration of a https://tools.ietf.org/html/rfc868[TIME] prococol client/server. The Netty
documentation provides client/server implementations of this protocol, we will focus on the integration of these
components.

== The TIME server

The original server example can be found http://netty.io/wiki/user-guide-for-4.x.html#wiki-h3-9[here].

The Vert.x timer server exposes a very simple API:

- a static method for creating a `TimeServer`
- the server `listen` and `close` life cycle methods
- the `requestHandler` for setting

[source,java]
----
public interface TimeServer {

  /**
   * @return a new time server
   */
  static TimeServer create(Vertx vertx) {
    return new TimeServerImpl(vertx);
  }

  /**
   * Set the handler to be called when a time request happens. The handler should complete
   * the future with the time value.
   *
   * @param handler the handler to be called
   * @return this object
   */
  TimeServer requestHandler(Handler<Future<Long>> handler);

  /**
   * Start and bind the time server.
   *
   * @param port the server port
   * @param host the server host
   * @param listenHandler the listen result handler
   */
  void listen(int port, String host, Handler<AsyncResult<Void>> listenHandler);

  /**
   * Close the time server.
   */
  void close();

}
----

A TIME server serving the current JVM time is then straighforward to implement:

[source,java]
----
Vertx vertx = Vertx.vertx();

// Create the time server
TimeServer server = TimeServer.create(vertx);
server.requestHandler(time -> {
  time.complete(System.currentTimeMillis());
});

// Start the server
server.listen(8037, "0.0.0.0", ar -> {
  if (ar.succeeded()) {
    System.out.println("Server started");
  } else {
    ar.cause().printStackTrace();
  }
});
----

Let's study now how this server can be implemented integrating the existing Netty implementation with Vert.x:

[source,java]
----
public class TimeServerImpl implements TimeServer {

  private final Vertx vertx;
  private Handler<Future<Long>> requestHandler;
  private ServerBootstrap bootstrap;
  private Channel channel;

  public TimeServerImpl(Vertx vertx) {
    this.vertx = vertx;
  }

  @Override
  public TimeServer requestHandler(Handler<Future<Long>> handler) {
    requestHandler = handler;
    return this;
  }

  @Override
  public void listen(int port, String host, Handler<AsyncResult<Void>> listenHandler) {
    if (requestHandler == null) {
      throw new IllegalStateException("No request handler set");
    }
    if (bootstrap != null) {
      throw new IllegalStateException("Already started");
    }

    // Get the current context as a Vert.x internal context
    ContextInternal context = (ContextInternal) vertx.getOrCreateContext();

    // The Vert.x internal context gives access to Netty's event loop
    EventLoop eventLoop = context.nettyEventLoop();

    // Create and configure the Netty server bootstrap
    bootstrap = new ServerBootstrap();
    bootstrap.channel(NioServerSocketChannel.class);
    bootstrap.group(eventLoop);
    bootstrap.childHandler(new ChannelInitializer<Channel>() {
      @Override
      protected void initChannel(Channel ch) throws Exception {
        ChannelPipeline pipeline = ch.pipeline();
        TimeServerHandler handler = new TimeServerHandler(context, requestHandler);
        pipeline.addLast(handler);
      }
    });

    // Bind the server socket
    ChannelFuture bindFuture = bootstrap.bind(host, port);
    bindFuture.addListener(new ChannelFutureListener() {
      @Override
      public void operationComplete(ChannelFuture future) throws Exception {

        // When we dispatch code to the Vert.x API we need to use executeFromIO
        context.executeFromIO(() -> {

          // Callback the listen handler either with a success or a failure
          if (future.isSuccess()) {
            channel = future.channel();
            listenHandler.handle(Future.succeededFuture(null));
          } else {
            listenHandler.handle(Future.failedFuture(future.cause()));
          }
        });
      }
    });
  }

  @Override
  public void close() {
    if (channel != null) {
      channel.close();
      channel = null;
    }
  }
}
----

The first point in this example is the usage of Vert.x `ContextInternal`, an extension of the
`io.vertx.core.Context` interface exposing the necessary bits for integrating the Netty API.

The context is obtained with `Vertx#getOrCreateContext()` method that returns the current execution context
or create a new one if necessary.

When used in a Verticle, `getOrCreateContext` return the context of this Verticle, when used in a non Vert.x
thread like a `main` or a unit test, it creates a new one and returns it.

Such context is always associated with a Netty event loop and thus using this context ensures our server
use the same event loop if one existed before or use a new one.

The method `ContextInternal#nettyEventLoop()` returns this particular event loop and we can use it when the
`ServerBoostrap` is created.

Now that we are more intimate with `ContextInternal`, let's talk of the `ContextInternal#executeFromIO(ContextTask)`
method. The `executeFromIO` method needs to be used when our server invokes application code, usually an handler
provided by the application before starting the server:

- listen handler
- request handler
- close handler
- etc...

When the context task is called, `executeFromIO` ensures that the current thread will be associated with
the execution context. Any uncaught exception thrown by this block will also be reported on the context, usually
such exception is either logged or passed to the `Context#exceptionHandler`.

We use `executeFromIO` to dispatch the result to the `listenHandler` to the application is aware of the bind result.

Now let's finish our server with the `TimeServerHandler`, which is pretty much an adaptation of the Netty's
original http://netty.io/wiki/user-guide-for-4.x.html#wiki-h3-9[`TimeServerHandler`]:

[source,java]
----
public class TimeServerHandler extends ChannelInboundHandlerAdapter {

  private ContextInternal context;
  private Handler<Future<Long>> requestHandler;

  public TimeServerHandler(ContextInternal context, Handler<Future<Long>> requestHandler) {
    this.context = context;
    this.requestHandler = requestHandler;
  }

  @Override
  public void channelActive(final ChannelHandlerContext ctx) {

    // Create a new blank future
    Future<Long> result = Future.future();

    // The handler is called when the user code complete the future
    result.setHandler(ar -> {

      // This block is pretty much borrowed from Netty's original example
      if (ar.succeeded()) {
        ByteBuf time = ctx.alloc().buffer(4);
        time.writeInt((int) (ar.result() / 1000L + 2208988800L));
        ChannelFuture f = ctx.writeAndFlush(time);
        f.addListener((ChannelFutureListener) channelFuture -> ctx.close());
      } else {
        ctx.close();
      }
    });

    // Dispatch to the request handler
    context.executeFromIO(() -> {
      requestHandler.handle(result);
    });
  }

  @Override
  public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
    ctx.close();
  }
}
----

Again here, we notice the usage of `executeFromIO` when a TIME request happens, the future to be completed is
passed to the `requestHandler`.

== The TIME client

todo.